import { initializeApp } from "https://www.gstatic.com/firebasejs/9.6.6/firebase-app.js";
import { getDatabase, ref, push, onValue, set, get, child, remove } from "https://www.gstatic.com/firebasejs/9.6.6/firebase-database.js";

const firebaseConfig = {
apiKey: "AIzaSyDhrBmnayr9BviXr3cQ2xt0XIniEajg0DQ",
authDomain: "light-up-8d93a.firebaseapp.com",
databaseURL: "https://light-up-8d93a-default-rtdb.firebaseio.com",
projectId: "light-up-8d93a",
storageBucket: "light-up-8d93a.appspot.com",
messagingSenderId: "219046596000",
appId: "1:219046596000:web:e5a1ad6d905e154e8768c5"
};

const app = initializeApp(firebaseConfig);
const db = getDatabase(app);
var reference;

const t = 'images/characters/Trump.png';
const k = 'images/characters/Kim.png';
const h = 'images/characters/Huan.png';
const bo = 'images/characters/Bo.png';
const ba = 'images/characters/Banh.png';
const n = 'images/characters/Nick.png';
const tn = 'images/characters/TungNui.png';
const e = 'images/characters/Elonmusk.png';

const ta = 'images/characters/Trump_avatar.png';
const ka = 'images/characters/Kim_avatar.png';
const ha = 'images/characters/Huan_avatar.png';
const boa = 'images/characters/Bo_avatar.png';
const baa = 'images/characters/Banh_avatar.png';
const na = 'images/characters/Nick_avatar.png';
const tna = 'images/characters/TungNui_avatar.png';
const ea = 'images/characters/Elonmusk_avatar.png';

function getAvatar(){
    var avatar = '';
    switch (document.getElementById('character_img').getAttribute('src')) {
        case t:
            avatar = ta;
            return avatar;
        case k:
            avatar = ka;
            return avatar;
        case h:
            avatar = ha;
            return avatar;
        case bo:
            avatar = boa;
        case ba:
            avatar = baa;
            return avatar;
        case n:
            avatar = na;
            return avatar;
        case tn:
            avatar = tna;
            return avatar;
        case e:
            avatar = ea;
            return avatar;
        };
}
const names = 
[
    "The Armor",
    "My Arsenal",
    "Annihilator",
    "Anomaly",
    "Arbitrage",
    "Team Arsenic",
    "Alien",
    "Abyss",
    "CrazyBull",
    "Agitator",
    "Agony",
    "Agrippa",
    "CargoKill",
    "Albatross",
    "Amaretto",
    "Amazon",
    "New Ambush",
    "Angon",
    "Animus",
    "Stream Elements",
    "Given Moment",
    "Trink",
    "Critical Role",
    "Digital",
    "Blood",
    "Sienna Princess",
    "Scalp",
    "Sky Bully",
    "Steel Foil",
    "Jawbone",
    "Cool Iris",
    "Tusk",
    "Albatross",
    "Bad Bunny",
    "Titanium",
    "Delivery Boy",
    "Dug Funnie",
    "Harry Dotter",
    "Manchu Man",
    "Mighty Mafia",
    "Anonymous Names",
    "CobraBite",
    "Bleed",
    "Fisheye",
    "Falcon",
    "Bullet",
    "Knuckles",
    "Silver Stone",
    "Roller Turtle",
    "RoarSweetie",
    "RedFeet",
    "Reed Lady",
    "Sythe",
    "Kneecap",
    "Acid Gosling",
    "Rubble",
    "Snake",
    "Hazzard",
    "Boar",
    "Devil Chick",
    "Capital F",
    "Ironsides",
    "Aspect",
    "Tweek",
    "Gut",
    "Blister",
    "Saint La-Z-Boy",
    "Geronimo",
    "Lynch",
    "Pursuit",
    "ScaryPumpkin",
    "Breaker",
    "Wardon",
    "Bowie",
    "Grizzly",
    "Iron-Cut",
    "Dexter",
    "Vulture",
    "Schizo",
    "Easy Sweep",
    "Razor",
    "Skull Crusher",
    "Dark Horse",
    "Cannon",
    "Sniper",
    "Darko",
    "Cannon",
    "Doz Killer",
    "Footslam",
    "Dust River",
    "Polaroid Pal",
    "Legend of Zelda",
    "Super Mario",
    "Dooming",
    "Pigeon",
    "Bowser",
    "Inch",
    "Final Fantasy",
    "Orphan",
    "Aqua",
    "Inferior",
    "Invaders",
    "Numb",
    "Penguin",
    "Nest",
    "Angry Stickman",
    "Warrior Dude",
    "Lara Croft",
    "Mario Kart",
    "Megaman",
    "Pokémonaa",
    "Pac-Man",
    "Baldur's Gate",
    "Harry Dotter",
    "Astro Ashe",
    "Airport Hobo",
    "Armadillo",
    "Gran Turismo",
    "Eerie Mizzen",
    "Devil Blade",
    "Parrot",
    "Pirate",
    "Mario RPG",
    "Decades",
    "Bouncing",
    "Flea",
    "Cat",
    "Diamond Gamer",
    "Meta Knight",
    "Cherry",
    "Mario Brothers",
    "Ori Super",
    "Nidoking",
    "Link Man",
    "Evil Genius",
    "Wario",
    "Raptor",
    "Valgazza",
    "Madden NFL",
    "Feta",
    "Alice",
    "Alex Jones",
    "Waluigi",
    "Diablo",
    "Dweezil",
    "Mim",
    "Zelda",
    "Weim",
    "Junk",
    "Thermajin",
    "Terraria",
    "Advanced Gaming",
    "Uncharted",
    "Peach",
    "Superboy",
    "Donkey Kong",
    "Dragon",
    "Fallout",
    "Raging Ogres",
    "Powerdrive",
    "Candy Cane",
    "Magic",
    "Minecraft",
    "Umara",
    "Pinball Tables",
    "Lazir",
    "Lara Croft",
    "Nihnum",
    "Trax",
    "Rose",
    "Fizz",
    "Finger of Death",
    "Criss Cross",
    "Bug Blitz",
    "Mad Dog",
    "Ballistic",
    "Uprising",
    "Aero",
    "K-9",
    "Wildcat",
    "Blonde",
    "Electric Saturn",
    "Fire Fish",
    "Mortar",
    "Steelshot",
    "Vein",
    "Socket",
    "Arsenal",
    "Wolf",
    "Skinner",
    "Fast Draw",
    "Khan",
    "Creep",
    "Claw",
    "Bitmap",
    "Rocky Highway",
    "Shadow Bishop",
    "DriftDetector",
    "Screw",
    "Black Mamba",
    "Tooth",
    "Torque",
    "Airport Hobo",
    "Wrath",
    "Mad Max",
    "ElactixNova",
    "Doom",
    "Cujo",
    "Betty Cricket",
    "Tomcat",
    "EyeShooter",
    "Disco Thunder",
    "Lash",
    "Rapid River",
    "Rotten Zucchini",
    "Apple Bob",
    "Clash of Cooks",
    "Crayon Crime",
    "Crazy Factory",
    "Bananas n Chips",
    "Cactus",
    "Call of Dowson",
    "Candy Crush",
    "Candy Land",
    "Danknado",
    "Dodge the Shoe",
    "Fortnite Couch",
    "Grandma's Nose",
    "Horse Herpes",
    "James Bomb",
    "Mario Kart",
    "Meme Man",
    "Minecraft",
    "Minecraft",
    "Mustache Smack",
    "Nesting Hens",
    "Nintendo",
    "Online Games",
    "Pacman",
    "Pinch the Pear",
    "Pokemon",
    "Pokemon",
    "Puds",
    "Skyrim",
    "Star Wars",
    "Super Mario",
    "Bad Soldier",
    "Popular Game",
    "Faulty Devils",
    "Plain Privilege",
    "Abnormal Vigor",
    "Trollers Goals",
    "Computing Tips",
    "Cookie Jar",
    "Greek Mythology",
    "Bob Vaginer",
    "Caps Gaming",
    "Penn National",
    "Chicky Fighter",
    "Satre Chair",
    "Monster Hunter",
    "Ram",
    "Reaper",
    "Wolverine",
    "Goshawk",
    "Carbine",
    "Hashtag",
    "Napoleon",
    "Cool Whip",
    "Big Papa",
    "Maximus",
    "Atilla",
    "Frenzy",
    "Siege",
    "Gnaw",
    "Sabotage",
    "Desperado",
    "FireByMisFire",
    "Lithium",
    "Minx",
    "Amazon",
    "Heroin",
    "Harlem",
    "Black Beauty",
    "Mannequin",
    "Terror",
    "Cosma",
    "Colada",
    "Thunderbird",
    "Lolita",
    "Pumps",
    "Femme Fatale",
    "Majesty",
    "Stiletto",
    "Infinity",
    "Enchantress",
    "Vixen",
    "Cougar",
    "Legacy",
    "Vanity",
    "Lotus",
    "Half Pint",
    "Wicked",
    "Nova",
    "Shadow",
    "Temperance",
    "Belladonna",
    "Tattoo",
    "Banshee",
    "Malice",
    "Geisha",
    "Carbon",
    "Roulette",
    "Siren",
    "Resin",
    "Calypso",
    "Ivy",
    "Cascade",
    "Raven",
    "Voodoo",
    "Ultra",
    "Nightmare",
    "Mirage",
    "T-Back",
    "Rogue",
    "Widow",
    "Xenon",
    "Beretta",
    "Countess",
    "Tequila",
    "Mademoiselle",
    "Enigma",
    "Anomaly",
    "Goddess",
    "Insomnia",
    "Velvet",
    "Nintendo Girl",
    "Kitty",
    "Alita",
    "Clementine",
    "Georgette",
    "Kaitlyn",
    "Angel",
    "Kitty",
    "Gamer Girl",
    "Nerdy Princess",
    "Sunshine",
    "Snow",
    "Serenity",
    "Nuzzle",
    "Climax",
    "Saki",
    "Eve",
    "Zlatan",
    "Remy",
    "Kiss",
    "Nana",
    "Belle",
    "Roses",
    "Cotton",
    "Gretchen",
    "Necromancer",
    "Rosalie",
    "Amy",
    "Kaylin",
    "Sakura",
    "Pudding",
    "Peach",
    "Rockstar",
    "Lily",
    "Karen",
    "Linda",
    "Annie",
    "Bridgette",
    "Legends Girl",
    "Queen",
    "Eris",
    "Pixel Princess",
    "Brigid",
    "Shelley",
    "Toffee",
    "Pat",
    "Fairies",
    "Lava",
    "Nina",
    "Minecraft Girl",
    "Lara",
    "Whitney",
    "Adelaide",
    "Jaime",
    "Loretta",
    "Cherry",
    "Gaming Girl",
    "Ashley",
    "Zombie Bunny",
    "Carrie",
    "Gwen",
    "Chloe",
    "Joy",
    "Blossom",
    "Dazzle",
    "Gamer Girl",
    "Grace",
    "Sugar",
    "Zoe",
    "Rory",
    "Shadow",
    "Livy",
    "Breeze",
    "Princess Avatar",
    "Leigh",
    "Lil Uzi",    
];

function getName(){
    var name = names[Math.floor(Math.random() * names.length)];
    if (document.getElementById('name-1d20').value != ""){
        name = document.getElementById('name-1d20').value;
        return name;
    }
    else{
        return name;
    }
}
function getPath(img){
    var path = img.src.split('/')[img.src.split('/').length - 1];
    return path;
}
var iMain = 1;

function addPlayer() {
    reference = ref(db, 'players/' + iMain.toString());

    get(reference).then((snapshot) => {
        if (snapshot.exists()) {
            if (iMain == 9){ alert("Room is full !"); } else {
            iMain++;
            console.log(iMain);
            reference = ref(db, 'players/' + iMain.toString());
            addPlayer();
            return; 
            }
        } else {
            set(reference, {
                name: getName(),
                flag: getPath(document.getElementById('flag')),
                avatar: getAvatar(),
                score: 0,
            });
            sessionStorage.id = iMain;
            window.location.href= "hall.html";
            return;
        }
    })    
}
document.getElementById('play_btn').addEventListener('click', addPlayer);

//end of main.html