const names = 
[
    "The Armor",
    "My Arsenal",
    "Annihilator",
    "Anomaly",
    "Arbitrage",
    "Team Arsenic",
    "Alien",
    "Abyss",
    "CrazyBull",
    "Agitator",
    "Agony",
    "Agrippa",
    "CargoKill",
    "Albatross",
    "Amaretto",
    "Amazon",
    "New Ambush",
    "Angon",
    "Animus",
    "Stream Elements",
    "Core Philosophies",
    "Given Moment",
    "Relative Performance",
    "Trink",
    "Flagship Property",
    "Critical Role",
    "Digital",
    "Blood",
    "Sienna Princess",
    "Scalp",
    "Sky Bully",
    "Steel Foil",
    "Jawbone",
    "Cool Iris",
    "Tusk",
    "Albatross",
    "Bad Bunny",
    "Titanium",
    "Delivery Boy",
    "Dug Funnie",
    "Gunsly Bruce Lee",
    "Harry Dotter",
    "Manchu Man",
    "Mighty Mafia",
    "Anonymous Names",
    "Homely Sharpshooters",
    "Investor Relations",
    "CobraBite",
    "Bleed",
    "Fisheye",
    "Sidewalk Enforcer",
    "Falcon",
    "Bullet",
    "Knuckles",
    "Silver Stone",
    "Roller Turtle",
    "RoarSweetie",
    "RedFeet",
    "Reed Lady",
    "Sythe",
    "Kneecap",
    "Acid Gosling",
    "Rubble",
    "Snake",
    "Hazzard",
    "Automatic Slicer",
    "Boar",
    "Devil Chick",
    "Accidental Genius",
    "Capital F",
    "Ironsides",
    "Aspect",
    "Tweek",
    "Gut",
    "Blister",
    "Saint La-Z-Boy",
    "Geronimo",
    "Lynch",
    "Pursuit",
    "ScaryPumpkin",
    "Breaker",
    "Wardon",
    "Bowie",
    "Grizzly",
    "Iron-Cut",
    "Dexter",
    "Vulture",
    "Schizo",
    "Easy Sweep",
    "Razor",
    "Skull Crusher",
    "Dark Horse",
    "Cannon",
    "Sniper",
    "Darko",
    "Cannon",
    "Doz Killer",
    "Footslam",
    "Dust River",
    "Polaroid Pal",
    "Legend of Zelda",
    "Demonic Criminals",
    "Blistered Outlaw",
    "Super Mario",
    "Dooming",
    "Pigeon",
    "Bowser",
    "Inch",
    "Final Fantasy",
    "Orphan",
    "Aqua",
    "Inferior",
    "Invaders",
    "Numb",
    "Penguin",
    "Nest",
    "Angry Stickman",
    "Warrior Dude",
    "Lara Croft",
    "Mario Kart",
    "The Legend of Zelda",
    "Super Smash Bros",
    "Megaman",
    "Pokémonaa",
    "Pac-Man",
    "Baldur's Gate",
    "Harry Dotter",
    "Astro Ashe",
    "Airport Hobo",
    "Armadillo",
    "Gran Turismo",
    "Eerie Mizzen",
    "Devil Blade",
    "Parrot",
    "Pirate",
    "Mario RPG",
    "Decades",
    "Bouncing",
    "Flea",
    "Cat",
    "Diamond Gamer",
    "Metal Gear Solid",
    "Meta Knight",
    "League of Legends",
    "Cherry",
    "Mario Brothers",
    "Ori Super",
    "Nidoking",
    "Link Man",
    "Evil Genius",
    "Wario",
    "Raptor",
    "Valgazza",
    "Madden NFL",
    "Super Smash Bros",
    "Feta",
    "Alice",
    "Alex Jones",
    "Waluigi",
    "Diablo",
    "Dweezil",
    "Mim",
    "Zelda",
    "Weim",
    "Junk",
    "Thermajin",
    "Terraria",
    "Advanced Gaming",
    "Uncharted",
    "Peach",
    "Superboy",
    "Donkey Kong",
    "Dragon",
    "Fallout",
    "Raging Ogres",
    "Powerdrive",
    "Candy Cane",
    "Magic",
    "Minecraft",
    "Umara",
    "Pinball Tables",
    "World of Warcraft",
    "Ninjas in Pajamas",
    "Lazir",
    "Lara Croft",
    "Nihnum",
    "Trax",
    "Rose",
    "Fizz",
    "Finger of Death",
    "Criss Cross",
    "Bug Blitz",
    "Mad Dog",
    "Ballistic",
    "Uprising",
    "Aero",
    "K-9",
    "Wildcat",
    "Blonde",
    "Electric Saturn",
    "Fire Fish",
    "Mortar",
    "Steelshot",
    "Vein",
    "Socket",
    "Arsenal",
    "Wolf",
    "Skinner",
    "Fast Draw",
    "Khan",
    "Creep",
    "Claw",
    "Bitmap",
    "Blistered Outlaw",
    "Rocky Highway",
    "Shadow Bishop",
    "DriftDetector",
    "Screw",
    "Black Mamba",
    "Tooth",
    "Torque",
    "Airport Hobo",
    "Wrath",
    "Mad Max",
    "ElactixNova",
    "Doom",
    "Cujo",
    "Betty Cricket",
    "Tomcat",
    "EyeShooter",
    "Disco Thunder",
    "Lash",
    "Rapid River",
    "Rotten Zucchini",
    "Sandwich Deliveries",
    "Sharks of Atlantis",
    "Apple Bob",
    "Clash of Cooks",
    "Crayon Crime",
    "Crazy Factory",
    "Bananas n Chips",
    "Cactus",
    "Call of Dowson",
    "Candy Crush",
    "Candy Land",
    "Danknado",
    "Dodge the Shoe",
    "Fortnite Couch",
    "Gardening Gophers",
    "Grand Theft Auto",
    "Grandma's Nose",
    "Horse Herpes",
    "James Bomb",
    "Kingdom of Memes",
    "Mario Kart",
    "Meme Man",
    "Minecraft",
    "Minecraft",
    "Mustache Smack",
    "My Little Balloon",
    "Nesting Hens",
    "Nintendo",
    "Online Games",
    "Pacman",
    "Pinch the Pear",
    "Pokemon",
    "Pokemon",
    "Puds",
    "Skyrim",
    "Star Wars",
    "Super Mario",
    "Superior Succotash",
    "Outrageous Dominance",
    "Bad Soldier",
    "Demonic Criminals",
    "Popular Game",
    "Faulty Devils",
    "Plain Privilege",
    "Abnormal Vigor",
    "Cloudy Perpetrator",
    "Trollers Goals",
    "Computing Tips",
    "Fanatical Tyranny",
    "Militaristic Fighting Machine",
    "Psychedelic Servicemen",
    "Disagreeable Liquidators",
    "Positive Attitude",
    "Cookie Jar",
    "Greek Mythology",
    "Bob Vaginer",
    "Caps Gaming",
    "Penn National",
    "Chicky Fighter",
    "Satre Chair",
    "Monster Hunter",
    "Ram",
    "Reaper",
    "Wolverine",
    "Goshawk",
    "Carbine",
    "Hashtag",
    "Napoleon",
    "Cool Whip",
    "Big Papa",
    "Maximus",
    "Atilla",
    "Frenzy",
    "Siege",
    "Drugstore Cowboy",
    "Gnaw",
    "Sabotage",
    "Desperado",
    "FireByMisFire",
    "Lithium",
    "Minx",
    "Amazon",
    "Heroin",
    "Harlem",
    "Black Beauty",
    "Mannequin",
    "Terror",
    "Cosma",
    "Colada",
    "Thunderbird",
    "Lolita",
    "Pumps",
    "Femme Fatale",
    "Majesty",
    "Stiletto",
    "Infinity",
    "Enchantress",
    "Vixen",
    "Cougar",
    "Legacy",
    "Vanity",
    "Lotus",
    "Half Pint",
    "Wicked",
    "Nova",
    "Shadow",
    "Temperance",
    "Belladonna",
    "Tattoo",
    "Banshee",
    "Malice",
    "Geisha",
    "Carbon",
    "Roulette",
    "Siren",
    "Resin",
    "Calypso",
    "Ivy",
    "Cascade",
    "Raven",
    "Voodoo",
    "Ultra",
    "Nightmare",
    "Mirage",
    "T-Back",
    "Rogue",
    "Widow",
    "Xenon",
    "Beretta",
    "Countess",
    "Tequila",
    "Mademoiselle",
    "Enigma",
    "Anomaly",
    "Goddess",
    "Insomnia",
    "Velvet",
    "Nintendo Girl",
    "Kitty",
    "Alita",
    "Clementine",
    "Georgette",
    "Kaitlyn",
    "Angel",
    "Kitty",
    "Gamer Girl",
    "Nerdy Princess",
    "Sunshine",
    "Snow",
    "Serenity",
    "Nuzzle",
    "Climax",
    "Saki",
    "Eve",
    "Zlatan",
    "Remy",
    "Kiss",
    "Nana",
    "Belle",
    "Roses",
    "Cotton",
    "Gretchen",
    "Necromancer",
    "Rosalie",
    "Amy",
    "Kaylin",
    "Sakura",
    "Pudding",
    "Peach",
    "Rockstar",
    "Lily",
    "Karen",
    "Linda",
    "Annie",
    "Bridgette",
    "Legends Girl",
    "Queen",
    "Eris",
    "Pixel Princess",
    "Brigid",
    "Shelley",
    "Toffee",
    "Pat",
    "Fairies",
    "Lava",
    "Nina",
    "Minecraft Girl",
    "Lara",
    "Whitney",
    "Adelaide",
    "Jaime",
    "Loretta",
    "Cherry",
    "Gaming Girl",
    "Ashley",
    "Zombie Bunny",
    "Carrie",
    "Gwen",
    "Chloe",
    "Joy",
    "Blossom",
    "Dazzle",
    "Gamer Girl",
    "Grace",
    "Sugar",
    "Zoe",
    "Rory",
    "Shadow",
    "Livy",
    "Breeze",
    "Princess Avatar",
    "Leigh",
    "Lil Uzi",    
];

var random_name = names[Math.floor(Math.random() * names.length)];

function generate_name(player){
    if (player_name.value != ""){
        player =  player_name.value;
    }
    else{
        player =  random_name;
    };
    return player;
};

function addPlayer(player, img){
    sessionStorage.name = player;
    sessionStorage.ava = img;
    location.href = "hall.html";
};

play_btn.addEventListener('click', function() {
    var img;
    var player;

    const t = 'images/characters/Trump.png';
    const k = 'images/characters/Kim.png';
    const h = 'images/characters/Huan.png';
    const b = 'images/characters/Bo.png';
    const ba = 'images/characters/Banh.png';
    const n = 'images/characters/Nick.png';
    const tn = 'images/characters/TungNui.png';
    const e = 'images/characters/Elonmusk.png';

    const ta = 'images/characters/Trump_avatar.png';
    const ka = 'images/characters/Kim_avatar.png';
    const ha = 'images/characters/Huan_avatar.png';
    const bav = 'images/characters/Bo_avatar.png';
    const baa = 'images/characters/Banh_avatar.png';
    const na = 'images/characters/Nick_avatar.png';
    const tna = 'images/characters/TungNui_avatar.png';
    const ea = 'images/characters/Elonmusk_avatar.png';

    switch (character_img.getAttribute('src')) {
        case t:
            img = ta;
            break;
        case k:
            img = ka;
            break;
        case h:
            img = ha;
            break;
        case b:
            img = bav;
            break;
        case ba:
            img = baa;
            break;
        case n:
            img = na;
            break;
        case tn:
            img = tna;
            break;
        case e:
            img = ea;
            break;
        };
        player = generate_name(player);
        
    addPlayer(player, img);
});